In [1]:
import pandas as pd
import numpy as np

In [43]:
food_desc = pd.read_csv('FOOD_DESC.csv')
food_group = pd.read_csv('FD_GROUP.csv')
langdesc = pd.read_csv('LANGDESC.csv')
langual = pd.read_csv('LANGUAL.csv')
weight = pd.read_csv('WEIGHT.csv')

In [44]:
master = pd.merge(food_desc, food_group, on='FdGrp_Cd', how='left')

In [46]:
food_desc.shape

(7793, 14)

In [45]:
master.shape

(7793, 15)

In [47]:
langs = pd.merge(langual, langdesc, on='Factor', how='left')

In [48]:
langs.head(20)

    NDB_No Factor                                     Description
0     2001  A0113                          SPICE OR HERB (US CFR)
1     2001  A1272                 0200 SPICES AND HERBS (USDA SR)
2     2001  B1356                                        ALLSPICE
3     2001  C0140  FRUIT, PEEL PRESENT, CORE, PIT OR SEED PRESENT
4     2001  E0106                                   FINELY GROUND
5     2001  F0003                                NOT HEAT-TREATED
6     2001  G0003                   COOKING METHOD NOT APPLICABLE
7     2001  H0138                                   WATER REMOVED
8     2001  J0141                                 NATURALLY DRIED
9     2001  J0170                                       SUN DRIED
10    2001  K0003                          NO PACKING MEDIUM USED
11    2001  M0001                 CONTAINER OR WRAPPING NOT KNOWN
12    2001  N0001                  FOOD CONTACT SURFACE NOT KNOWN
13    2001  P0024                HUMAN FOOD, NO AGE SPECIFICATION
14    2002  A0113                          SPICE OR HERB (US CFR)
15    2002  A1272                 0200 SPICES AND HERBS (USDA SR)
16    2002  B1296                                           ANISE
17    2002  C0167                                           FRUIT
18    2002  E0150                            WHOLE, NATURAL SHAPE
19    2002  F0003                                NOT HEAT-TREATED

In [49]:
langs = langs[langs.Factor.str.startswith('B')]

In [50]:
mtr_lng = pd.merge(langs, master[['NDB_No', 'Long_Desc']], on='NDB_No', how='left')

In [52]:
master = pd.merge(master, mtr_lng[['NDB_No','Description']], on='NDB_No', how='outer')

In [54]:
master.shape

(7793, 16)

In [9]:
master.loc[:, 'FdGrp_desc'].value_counts()

Vegetables and Vegetable Products    775
Beef Products                        476
Pork Products                        308
Fruits and Fruit Juices              298
Poultry Products                     236
Legumes and Legume Products          188
Cereal Grains and Pasta              165
Nut and Seed Products                127
Spices and Herbs                      54
Name: FdGrp_desc, dtype: int64

In [10]:
weight.head(50)

,NDB_No,Seq,Amount,Msre_Desc,Gm_Wgt,Num_Data_pts,Std_Dev
0,1001,1,1.0,"pat (1"" sq, 1/3"" high)",5.00,NaN,NaN
1,1001,2,1.0,tbsp,14.20,NaN,NaN
2,1001,3,1.0,cup,227.00,NaN,NaN
3,1001,4,1.0,stick,113.00,NaN,NaN
4,1002,1,1.0,"pat (1"" sq, 1/3"" high)",3.80,NaN,NaN
5,1002,2,1.0,tbsp,9.40,NaN,NaN
6,1002,3,1.0,cup,151.00,NaN,NaN
7,1002,4,1.0,stick,76.00,NaN,NaN
8,1003,1,1.0,tbsp,12.80,NaN,NaN
9,1003,2,1.0,cup,205.00,NaN,NaN
10,1004,1,1.0,oz,28.35,NaN,NaN
11,1004,2,1.0,cubic inch,17.00,NaN,NaN
12,1004,3,1.0,"cup, crumbled, not packed",135.00,NaN,NaN
13,1005,1,1.0,"cup, diced",132.00,NaN,NaN
14,1005,2,1.0,"cup, shredded",113.00,NaN,NaN
15,1005,3,1.0,oz,28.35,NaN,NaN
16,1005,4,1.0,cubic inch,17.00,NaN,NaN
17,1005,5,1.0,slice (1 oz),28.00,NaN,NaN
18,1006,1,1.0,oz,28.35,NaN,NaN
19,1006,2,1.0,"cup, sliced",144.00,NaN,NaN
20,1006,3,1.0,"cup, melted",240.00,NaN,NaN
21,1006,4,1.0,cubic inch,17.00,NaN,NaN
22,1006,5,1.0,package (4.5 oz),128.00,NaN,NaN
23,1007,1,1.0,oz,28.35,NaN,NaN
24,1007,2,1.0,cup,246.00,NaN,NaN
25,1007,3,1.0,cubic inch,17.00,NaN,NaN
26,1007,4,1.0,wedge (1.33 oz),38.00,NaN,NaN
27,1008,1,1.0,oz,28.35,NaN,NaN
28,1009,1,1.0,"cup, diced",132.00,NaN,NaN
29,1009,2,1.0,"cup, melted",244.00,NaN,NaN
30,1009,3,1.0,"cup, shredded",113.00,NaN,NaN
31,1009,4,1.0,oz,28.35,NaN,NaN
32,1009,5,1.0,cubic inch,17.00,NaN,NaN
33,1009,6,1.0,slice (1 oz),28.00,NaN,NaN
34,1010,1,1.0,oz,28.35,NaN,NaN
35,1011,1,1.0,"cup, diced",132.00,NaN,NaN
36,1011,2,1.0,"cup, shredded",113.00,NaN,NaN
37,1011,3,1.0,oz,28.35,NaN,NaN
38,1011,4,1.0,cubic inch,17.00,NaN,NaN
39,1011,5,1.0,slice (1 oz),28.00,NaN,NaN
40,1012,1,4.0,oz,113.00,NaN,NaN
41,1012,2,1.0,"cup, large curd (not packed)",210.00,NaN,NaN
42,1012,3,1.0,"cup, small curd (not packed)",225.00,NaN,NaN
43,1013,1,4.0,oz,113.00,NaN,NaN
44,1013,2,1.0,cup (not packed),226.00,NaN,NaN
45,1014,1,1.0,cup (not packed),145.00,NaN,NaN
46,1014,2,4.0,oz,113.00,NaN,NaN
47,1015,1,4.0,oz,113.00,NaN,NaN
48,1015,2,1.0,cup (not packed),226.00,NaN,NaN
49,1016,1,4.0,oz,113.00,NaN,NaN

In [11]:
merged_weight = pd.merge(weight, master[['NDB_No', 'Long_Desc']], on='NDB_No')

In [12]:
master.head()

,NDB_No,FdGrp_Cd,Long_Desc,Shrt_Desc,Com_Name,ManufacName,Survey,Ref_Desc,Refuse,Sci_Name,N_FActor,Pro_Factor_,Fat_Factor_,CHO_Factor,FdGrp_desc,Description
0,2001,200,"Spices, allspice, ground","ALLSPICE,GROUND",NaN,NaN,NaN,NaN,0.0,Pimenta dioica,6.25,3.36,8.37,2.35,Spices and Herbs,ALLSPICE
1,2002,200,"Spices, anise seed",ANISE SEED,NaN,NaN,NaN,NaN,0.0,Pimpinella anisum,6.25,3.36,8.37,2.90,Spices and Herbs,ANISE
2,2003,200,"Spices, basil, dried","SPICES,BASIL,DRIED",NaN,NaN,Y,NaN,0.0,Ocimum basilicum,6.25,2.44,8.37,3.00,Spices and Herbs,"BASIL, SWEET"
3,2004,200,"Spices, bay leaf","SPICES,BAY LEAF",NaN,NaN,NaN,NaN,0.0,Laurus nobilis,6.25,2.44,8.37,3.00,Spices and Herbs,BAY
4,2005,200,"Spices, caraway seed",CARAWAY SEED,NaN,NaN,Y,NaN,0.0,Carum carvi,6.25,3.36,8.37,2.90,Spices and Herbs,CARAWAY

In [13]:
from fuzzywuzzy import process, fuzz

In [55]:
choices = master.Description.values
choices2 = master.Long_Desc.values

In [76]:
ing = "lentil"
process.extract(ing, choices, scorer=fuzz.token_set_ratio )

[('LENTIL', 100),
 ('LENTIL', 100),
 ('LENTIL', 100),
 ('LENTIL', 100),
 ('LENTIL', 100)]

In [77]:
process.extract(ing, choices2, scorer=fuzz.token_set_ratio)

[('Soup, lentil with ham, canned, ready-to-serve', 100),
 ('SMART SOUP, French Lentil', 100),
 ('Lentils, raw', 71),
 ('Oil, hazelnut', 56),
 ('Oil, almond', 50)]

In [78]:
master[master.Description == 'LENTIL']

,NDB_No,FdGrp_Cd,Long_Desc,Shrt_Desc,Com_Name,ManufacName,Survey,Ref_Desc,Refuse,Sci_Name,N_FActor,Pro_Factor_,Fat_Factor_,CHO_Factor,FdGrp_desc,Description
2613,11248,1100,"Lentils, sprouted, raw","LENTILS,SPROUTED,RAW",NaN,NaN,NaN,NaN,0.0,Lens culinaris,6.25,2.44,8.37,3.57,Vegetables and Vegetable Products,LENTIL
2614,11249,1100,"Lentils, sprouted, cooked, stir-fried, without...","LENTILS,SPROUTED,CKD,STIR-FRIED,WO/SALT",NaN,NaN,NaN,NaN,0.0,NaN,6.25,2.44,8.37,3.57,Vegetables and Vegetable Products,LENTIL
3147,11926,1100,"Lentils, sprouted, cooked, stir-fried, with salt","LENTILS,SPROUTED,CKD,STIR-FRIED,W/SALT",NaN,NaN,NaN,NaN,0.0,NaN,6.25,2.44,8.37,3.57,Vegetables and Vegetable Products,LENTIL
4410,16069,1600,"Lentils, raw","LENTILS,RAW",NaN,NaN,Y,NaN,0.0,Lens culinaris,6.25,3.47,8.37,4.07,Legumes and Legume Products,LENTIL
4411,16070,1600,"Lentils, mature seeds, cooked, boiled, without...","LENTILS,MATURE SEEDS,CKD,BLD,WO/SALT",NaN,NaN,Y,NaN,0.0,NaN,6.25,3.47,8.37,4.07,Legumes and Legume Products,LENTIL
4587,16370,1600,"Lentils, mature seeds, cooked, boiled, with salt","LENTILS,MATURE SEEDS,CKD,BLD,W/SALT",NaN,NaN,NaN,NaN,0.0,NaN,6.25,3.47,8.37,4.07,Legumes and Legume Products,LENTIL

In [42]:
master.shape

(2627, 16)

So my general strategy for linking this list with my database will be too:
    - check scores from pattern matching using fuzzy from B column of linual and
      the Long_Desc from FOOD_DESC
    - of those two scores, take which ever is the highest 
    - if several are highest take an average of the values I want or majority take all
    - look up item on the table and use the values I want (food group, Description, NDB_No for 
      adding measurement values later)